testGetPiece:-
  initBoard(Board),
  printBoard(Board),
  write('--- Test getPiece ---'),nl,
  write('Test 1: X=1, Y=1'),nl,
  getPiece(Board, 1, 1, Piece1),
  write('piece : '),
  write(Piece1),nl,
  Piece1 == 11,
  write('Test 2: X=2, Y=3'),nl,
  getPiece(Board, 2, 3, Piece2),
  write('piece : '),
  write(Piece2),nl,
  Piece2 == 23,
  write('Test 3: X=3, Y=2'),nl,
  getPiece(Board, 3, 2, Piece3),
  write('piece : '),
  write(Piece3),nl,
  Piece3 == 32.
