testDoEat:-
  initBoard(Board),
  printBoard(Board),
  %% test eat 
  write('--- Test doEat ---'),nl,
  write('Move white in (2,4) to (3,5)'),nl,
  doMove(Board, 2, 4, 3, 5, Board1),
  write('Move white in (3,5) to (4,6)'),nl,
  doMove(Board1, 3, 5, 4, 6, Board2),
  write('Black in (5,7) eats white in (4,6)'),nl,
  doEat(Board2, 5, 7, 3, 5, Board3),
  printBoard(Board3),
  zombieToEmpty(Board3, Board4),
  write('Move black in (4,8) to (5,7)'),nl,
  doMove(Board4, 4, 8, 5, 7, Board5),
  write('White in (4,4) eats black in (3,5) and in (3,7) and in (5,7)'),nl,
  doEat(Board5, 4, 4, 2, 6, Board6),
  doEat(Board6, 2, 6, 4, 8, Board7),
  doEat(Board7, 4, 8, 6, 6, Board8),
  printBoard(Board8),
  write('Replace all zombies by empties'),nl,
  zombieToEmpty(Board8, Board9),
  printBoard(Board9),
  write('OK'),nl,
 
  write('--- Test doEat Completed ---'),nl.
