testCheckMove:-
  initBoard(Board),
  printBoard(Board),
  %% test eat and move
  write('--- Test CheckMove ---'),nl,
  write('Test 1: White (2,4) to (3,5) - Valid'),nl,
  checkMove(Board, 2, 4, 3, 5),
  write('OK'),nl,
  write('Test 2: White (2,4) to (5,5) - Valid'),nl,
  checkMove(Board, 2, 4, 1, 5),
  write('OK'),nl,
  write('Test 3: White (2,4) to (3,5) - Valid'),nl,
  checkMove(Board, 3, 7, 4, 6),
  write('OK'),nl,
  write('Test 4: White (2,4) to (3,5) - Valid'),nl,
  checkMove(Board, 3, 7, 2, 6),
  write('OK'),nl,
  write('Test 5: White (1,7) to (0,6) - Error destination out of limit'),nl,
  not(checkMove(Board,1, 7, 0, 6)),
  write('OK'),nl,
  write('Test 6: No pawn (2,7) to (3,6) - Error no pawn selected'),nl,
  not(checkMove(Board,2, 7, 3, 6)),
  write('OK'),nl,
  write('Test 7: White (1,7) to (2,7) - Move not allowed'),nl,
  not(checkMove(Board,1, 7, 2, 7)),
  write('OK'),nl,
  write('Test 8: White (1,7) to (1,8) - Move not allowed'),nl,
  not(checkMove(Board,1, 7, 1, 8)),
  write('OK'),nl,
  write('Test 9: White (8,2) to (7,4) - destination not empty'),nl,
  not(checkMove(Board,8, 2, 7, 4)),
  write('OK'),nl,
  write('--- Test Move Completed ---'),nl.
